LISTENING_PORT = 8468  # Kademlia port
BOOTSTRAP_NODE_IP = "10.0.0.216"
SOCKET_LISTENING_PORT = 8469  # Socket port
FILE_TRANSFER_PORT = 8470
ACK_WAIT_TIMEOUT = 10
TRACKED_FOLDER_PATH = "C:\\Users\\chris\\Desktop\\TestFolder"
FILE_METADATA_KEY_PREFIX = "file_metadata_"
